# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
    inputs:
      username: 
      description: 'A username passed from the caller workflow'
      default: 'Ramesh'
      required: false
      type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world! My name is ${{inputs.username}}

      - name: Run a multi-line script
        run: ls; cat /etc/os-release
      - name: Github context veriable
        run: echo ${{github.env}} and ${{github.workflow}} and ${{github.repositoryUrl}} and ${{github.triggering_actor}} and ${{github.retention_days}} and ${{github.repository_owner}}
