name: Creting bucket

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  bucket:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 1day

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
      - name: Terraform plan
        run: terraform plan
     # - name: Terraform Cretae
      #  run: |
       #   terraform apply \
        #    -auto-approve
