name: If demo
on: 
  push:
    brnaches:
      - main
      #- devlop
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Run if branch is main
        if: github.ref_name == 'main'
        run: echo "Running for main branch1"
      - name: Run this step
        run: echo "running this step"
