name: Deploy html to s3
on: push
permissions:
  id-token: write
  contents: read
jobs: 
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 3day    
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: List of file
        run: ls 

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
      - name: Upload files to S3
        run: |
          aws s3 cp ./index.html s3://s3-test357-dev/  --recursive         
